# Generated by Django 4.2.2 on 2023-06-09 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 9, 6, 21, 37, 730759, tzinfo=datetime.timezone.utc)),
        ),
    ]
