# Generated by Django 4.2.2 on 2023-06-09 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0002_alter_task_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 9, 6, 30, 6, 921170, tzinfo=datetime.timezone.utc)),
        ),
    ]
