# Generated by Django 4.2.2 on 2023-06-09 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0003_alter_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 9, 10, 26, 16, 437470, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
